server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/counter?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: 31415926
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 6000


mybatis:
  mapperLocations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'


cacheexpire:
  captcha: 100
  account: 3600
  order: 36000

counter:
  dataCenterId: 0
  id: 1000
  workerId: 0
